CREATE TABLE users (
    id BIGINT(20) NOT NULL AUTO_INCREMENT,
    firstName VARCHAR(255) NOT NULL,
    secondName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
)